In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd
pd = pd.read_csv('machine.csv', skipinitialspace = True)
pd

vendorName          model  myct  mmin   mmax  cach  chmin  chmax  prp  erp
0       amdahl         470v/7    29  8000  32000    32      8     32  269  253
1       amdahl        470v/7a    29  8000  32000    32      8     32  220  253
2       amdahl        470v/7b    29  8000  32000    32      8     32  172  253
3       amdahl        470v/7c    29  8000  16000    32      8     16  132  132
4       amdahl         470v/b    26  8000  32000    64      8     32  318  290
..         ...            ...   ...   ...    ...   ...    ...    ...  ...  ...
203     sperry           80/8   124  1000   8000     0      1      8   42   37
204     sperry  90/80-model-3    98  1000   8000    32      2      8   46   50
205     sratus             32   125  2000   8000     0      2     14   52   41
206       wang         vs-100   480   512   8000    32      0      0   67   47
207       wang          vs-90   480  1000   4000     0      0      0   45   25

[208 rows x 10 columns]

In [2]:
pd = pd.drop(columns=['vendorName', 'model'])
pd

myct  mmin   mmax  cach  chmin  chmax  prp  erp
0      29  8000  32000    32      8     32  269  253
1      29  8000  32000    32      8     32  220  253
2      29  8000  32000    32      8     32  172  253
3      29  8000  16000    32      8     16  132  132
4      26  8000  32000    64      8     32  318  290
..    ...   ...    ...   ...    ...    ...  ...  ...
203   124  1000   8000     0      1      8   42   37
204    98  1000   8000    32      2      8   46   50
205   125  2000   8000     0      2     14   52   41
206   480   512   8000    32      0      0   67   47
207   480  1000   4000     0      0      0   45   25

[208 rows x 8 columns]

In [3]:
x = np.array(pd[pd.columns[0:7]])
x

array([[   29,  8000, 32000, ...,     8,    32,   269],
       [   29,  8000, 32000, ...,     8,    32,   220],
       [   29,  8000, 32000, ...,     8,    32,   172],
       ...,
       [  125,  2000,  8000, ...,     2,    14,    52],
       [  480,   512,  8000, ...,     0,     0,    67],
       [  480,  1000,  4000, ...,     0,     0,    45]], dtype=int64)

In [4]:
y = np.array(pd[pd.columns[7:8]])
y

array([[ 253],
       [ 253],
       [ 253],
       [ 132],
       [ 290],
       [ 381],
       [ 381],
       [ 749],
       [1238],
       [  23],
       [  24],
       [  70],
       [ 117],
       [  15],
       [  64],
       [  23],
       [  29],
       [  22],
       [ 124],
       [  35],
       [  39],
       [  40],
       [  45],
       [  28],
       [  21],
       [  28],
       [  22],
       [  28],
       [  27],
       [ 102],
       [ 102],
       [  74],
       [  74],
       [ 138],
       [ 136],
       [  23],
       [  29],
       [  44],
       [  30],
       [  41],
       [  74],
       [  74],
       [  74],
       [  54],
       [  41],
       [  18],
       [  28],
       [  36],
       [  38],
       [  34],
       [  19],
       [  72],
       [  36],
       [  30],
       [  56],
       [  42],
       [  34],
       [  34],
       [  34],
       [  34],
       [  34],
       [  19],
       [  75],
       [ 113],
       [ 157],
       [  18],
       [  

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3)

In [6]:
x_train

array([[   56,  4000, 12000, ...,     1,     8,    42],
       [  105,  1000,  4000, ...,     3,    24,    32],
       [  225,  1000,  4000, ...,     3,     6,    24],
       ...,
       [   38,  8000, 24000, ...,     4,     8,   140],
       [  110,  5000,  5000, ...,     8,    64,   120],
       [  400,   512,  3500, ...,     1,     6,    40]], dtype=int64)

In [7]:
reg = LinearRegression().fit(x_train,y_train)

In [8]:
reg.predict(x_test)

array([[ 1.03441307e+01],
       [ 1.19851595e+02],
       [ 6.13338067e+01],
       [ 1.76282163e+01],
       [-1.05537980e+01],
       [-1.44132926e+01],
       [ 5.96738633e+01],
       [-1.96857831e+00],
       [-1.42117468e+01],
       [ 1.08266454e+02],
       [ 6.38705519e+01],
       [ 5.99731603e+01],
       [ 3.83333467e+02],
       [ 4.62873261e+01],
       [ 2.32660472e+02],
       [-2.62455465e+00],
       [ 4.61320222e+01],
       [ 3.73325344e+01],
       [ 3.81461419e+01],
       [ 3.69370504e+01],
       [ 1.36401725e+02],
       [ 2.99210124e+02],
       [ 1.55016075e+01],
       [ 1.50442313e+01],
       [ 1.76083632e+01],
       [ 1.96174457e+01],
       [ 1.33689150e+02],
       [ 4.00865049e+01],
       [ 8.94531408e+00],
       [ 2.92449546e+00],
       [ 7.74214498e+01],
       [ 3.51846393e+01],
       [ 9.93586548e+01],
       [ 3.40498324e+01],
       [ 2.33871849e+01],
       [ 7.85383758e+00],
       [ 3.20658842e+01],
       [ 4.02614720e+01],
       [ 1.5

In [9]:
#check the accuracy 
reg.score(x_test,y_test)

0.9766392522523316