In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
pd = pd.read_csv('banknote.csv', skipinitialspace = True)
pd

Column1   Column2  Column3  Column4  Column5
0     3.62160   8.66610  -2.8073 -0.44699        0
1     4.54590   8.16740  -2.4586 -1.46210        0
2     3.86600  -2.63830   1.9242  0.10645        0
3     3.45660   9.52280  -4.0112 -3.59440        0
4     0.32924  -4.45520   4.5718 -0.98880        0
...       ...       ...      ...      ...      ...
1367  0.40614   1.34920  -1.4501 -0.55949        1
1368 -1.38870  -4.87730   6.4774  0.34179        1
1369 -3.75030 -13.45860  17.5932 -2.77710        1
1370 -3.56370  -8.38270  12.3930 -1.28230        1
1371 -2.54190  -0.65804   2.6842  1.19520        1

[1372 rows x 5 columns]

In [2]:
x = np.array(pd[pd.columns[0:4]])
x

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [3]:
y = np.array(pd[pd.columns[4:5]])
y

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [4]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=1, stratify=y)

In [5]:
# Create KNN classifier
# instantiate learning model (k = 5)
knn = KNeighborsClassifier(n_neighbors = 5)

In [6]:
x_train[0:5]

array([[-1.2537 , 10.8803 ,  1.931  , -4.3237 ],
       [-1.9881 ,  0.99945, -0.28562, -0.70044],
       [ 4.0026 , -3.5943 ,  3.5573 ,  0.26809],
       [-2.2173 ,  1.4671 , -0.72689, -1.1724 ],
       [ 4.7114 ,  2.0755 , -0.2702 ,  1.2379 ]])

In [7]:
y_train[0:5]

array([[0],
       [1],
       [0],
       [1],
       [0]], dtype=int64)

In [8]:
knn.fit(x_train,y_train.ravel())

KNeighborsClassifier()

In [9]:
knn.predict(x_test)

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,

In [10]:
#check accuracy of our model based on the test data
knn.score(x_test, y_test)

1.0